/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace IAgentVault {
  export type RulesStruct = {
    maxPerTransaction: BigNumberish;
    dailyLimit: BigNumberish;
    monthlyLimit: BigNumberish;
    allowedRecipients: AddressLike[];
    allowedTokens: AddressLike[];
    validFrom: BigNumberish;
    validUntil: BigNumberish;
  };

  export type RulesStructOutput = [
    maxPerTransaction: bigint,
    dailyLimit: bigint,
    monthlyLimit: bigint,
    allowedRecipients: string[],
    allowedTokens: string[],
    validFrom: bigint,
    validUntil: bigint
  ] & {
    maxPerTransaction: bigint;
    dailyLimit: bigint;
    monthlyLimit: bigint;
    allowedRecipients: string[];
    allowedTokens: string[];
    validFrom: bigint;
    validUntil: bigint;
  };
}

export interface AgentVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createVault"
      | "deposit"
      | "depositToken"
      | "ethBalances"
      | "getRemainingBudget"
      | "getRules"
      | "nextVaultId"
      | "revokeAgent"
      | "setRules"
      | "spend"
      | "tokenBalances"
      | "updateAgent"
      | "vaults"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentRevoked"
      | "AgentUpdated"
      | "Deposited"
      | "RulesSet"
      | "Spent"
      | "VaultCreated"
      | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositToken",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ethBalances",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRemainingBudget",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRules",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextVaultId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAgent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setRules",
    values: [BigNumberish, IAgentVault.RulesStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "spend",
    values: [BigNumberish, AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenBalances",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAgent",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vaults",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "createVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ethBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRemainingBudget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRules", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextVaultId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setRules", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "spend", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokenBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vaults", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace AgentRevokedEvent {
  export type InputTuple = [vaultId: BigNumberish, agent: AddressLike];
  export type OutputTuple = [vaultId: bigint, agent: string];
  export interface OutputObject {
    vaultId: bigint;
    agent: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentUpdatedEvent {
  export type InputTuple = [
    vaultId: BigNumberish,
    oldAgent: AddressLike,
    newAgent: AddressLike
  ];
  export type OutputTuple = [
    vaultId: bigint,
    oldAgent: string,
    newAgent: string
  ];
  export interface OutputObject {
    vaultId: bigint;
    oldAgent: string;
    newAgent: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositedEvent {
  export type InputTuple = [
    vaultId: BigNumberish,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [vaultId: bigint, token: string, amount: bigint];
  export interface OutputObject {
    vaultId: bigint;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RulesSetEvent {
  export type InputTuple = [vaultId: BigNumberish];
  export type OutputTuple = [vaultId: bigint];
  export interface OutputObject {
    vaultId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SpentEvent {
  export type InputTuple = [
    vaultId: BigNumberish,
    token: AddressLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    vaultId: bigint,
    token: string,
    to: string,
    amount: bigint
  ];
  export interface OutputObject {
    vaultId: bigint;
    token: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultCreatedEvent {
  export type InputTuple = [
    vaultId: BigNumberish,
    owner: AddressLike,
    agent: AddressLike
  ];
  export type OutputTuple = [vaultId: bigint, owner: string, agent: string];
  export interface OutputObject {
    vaultId: bigint;
    owner: string;
    agent: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [
    vaultId: BigNumberish,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [vaultId: bigint, token: string, amount: bigint];
  export interface OutputObject {
    vaultId: bigint;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentVault extends BaseContract {
  connect(runner?: ContractRunner | null): AgentVault;
  waitForDeployment(): Promise<this>;

  interface: AgentVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createVault: TypedContractMethod<
    [agent: AddressLike],
    [bigint],
    "nonpayable"
  >;

  deposit: TypedContractMethod<[vaultId: BigNumberish], [void], "payable">;

  depositToken: TypedContractMethod<
    [vaultId: BigNumberish, token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  ethBalances: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  getRemainingBudget: TypedContractMethod<
    [vaultId: BigNumberish, token: AddressLike],
    [[bigint, bigint] & { dailyRemaining: bigint; monthlyRemaining: bigint }],
    "view"
  >;

  getRules: TypedContractMethod<
    [vaultId: BigNumberish],
    [IAgentVault.RulesStructOutput],
    "view"
  >;

  nextVaultId: TypedContractMethod<[], [bigint], "view">;

  revokeAgent: TypedContractMethod<
    [vaultId: BigNumberish],
    [void],
    "nonpayable"
  >;

  setRules: TypedContractMethod<
    [vaultId: BigNumberish, rules: IAgentVault.RulesStruct],
    [void],
    "nonpayable"
  >;

  spend: TypedContractMethod<
    [
      vaultId: BigNumberish,
      to: AddressLike,
      amount: BigNumberish,
      token: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  tokenBalances: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  updateAgent: TypedContractMethod<
    [vaultId: BigNumberish, newAgent: AddressLike],
    [void],
    "nonpayable"
  >;

  vaults: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, boolean] & {
        owner: string;
        agent: string;
        rulesSet: boolean;
      }
    ],
    "view"
  >;

  withdraw: TypedContractMethod<
    [vaultId: BigNumberish, token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createVault"
  ): TypedContractMethod<[agent: AddressLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[vaultId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "depositToken"
  ): TypedContractMethod<
    [vaultId: BigNumberish, token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ethBalances"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRemainingBudget"
  ): TypedContractMethod<
    [vaultId: BigNumberish, token: AddressLike],
    [[bigint, bigint] & { dailyRemaining: bigint; monthlyRemaining: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRules"
  ): TypedContractMethod<
    [vaultId: BigNumberish],
    [IAgentVault.RulesStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextVaultId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "revokeAgent"
  ): TypedContractMethod<[vaultId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRules"
  ): TypedContractMethod<
    [vaultId: BigNumberish, rules: IAgentVault.RulesStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "spend"
  ): TypedContractMethod<
    [
      vaultId: BigNumberish,
      to: AddressLike,
      amount: BigNumberish,
      token: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "tokenBalances"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "updateAgent"
  ): TypedContractMethod<
    [vaultId: BigNumberish, newAgent: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "vaults"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, boolean] & {
        owner: string;
        agent: string;
        rulesSet: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [vaultId: BigNumberish, token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AgentRevoked"
  ): TypedContractEvent<
    AgentRevokedEvent.InputTuple,
    AgentRevokedEvent.OutputTuple,
    AgentRevokedEvent.OutputObject
  >;
  getEvent(
    key: "AgentUpdated"
  ): TypedContractEvent<
    AgentUpdatedEvent.InputTuple,
    AgentUpdatedEvent.OutputTuple,
    AgentUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "RulesSet"
  ): TypedContractEvent<
    RulesSetEvent.InputTuple,
    RulesSetEvent.OutputTuple,
    RulesSetEvent.OutputObject
  >;
  getEvent(
    key: "Spent"
  ): TypedContractEvent<
    SpentEvent.InputTuple,
    SpentEvent.OutputTuple,
    SpentEvent.OutputObject
  >;
  getEvent(
    key: "VaultCreated"
  ): TypedContractEvent<
    VaultCreatedEvent.InputTuple,
    VaultCreatedEvent.OutputTuple,
    VaultCreatedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "AgentRevoked(uint256,address)": TypedContractEvent<
      AgentRevokedEvent.InputTuple,
      AgentRevokedEvent.OutputTuple,
      AgentRevokedEvent.OutputObject
    >;
    AgentRevoked: TypedContractEvent<
      AgentRevokedEvent.InputTuple,
      AgentRevokedEvent.OutputTuple,
      AgentRevokedEvent.OutputObject
    >;

    "AgentUpdated(uint256,address,address)": TypedContractEvent<
      AgentUpdatedEvent.InputTuple,
      AgentUpdatedEvent.OutputTuple,
      AgentUpdatedEvent.OutputObject
    >;
    AgentUpdated: TypedContractEvent<
      AgentUpdatedEvent.InputTuple,
      AgentUpdatedEvent.OutputTuple,
      AgentUpdatedEvent.OutputObject
    >;

    "Deposited(uint256,address,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "RulesSet(uint256)": TypedContractEvent<
      RulesSetEvent.InputTuple,
      RulesSetEvent.OutputTuple,
      RulesSetEvent.OutputObject
    >;
    RulesSet: TypedContractEvent<
      RulesSetEvent.InputTuple,
      RulesSetEvent.OutputTuple,
      RulesSetEvent.OutputObject
    >;

    "Spent(uint256,address,address,uint256)": TypedContractEvent<
      SpentEvent.InputTuple,
      SpentEvent.OutputTuple,
      SpentEvent.OutputObject
    >;
    Spent: TypedContractEvent<
      SpentEvent.InputTuple,
      SpentEvent.OutputTuple,
      SpentEvent.OutputObject
    >;

    "VaultCreated(uint256,address,address)": TypedContractEvent<
      VaultCreatedEvent.InputTuple,
      VaultCreatedEvent.OutputTuple,
      VaultCreatedEvent.OutputObject
    >;
    VaultCreated: TypedContractEvent<
      VaultCreatedEvent.InputTuple,
      VaultCreatedEvent.OutputTuple,
      VaultCreatedEvent.OutputObject
    >;

    "Withdrawn(uint256,address,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
